title:  Калина Алексей
tagline:  блог программиста

disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/AlexeyKalina'}
- {icon: 'envelope', link: 'mailto:alexey.kalina96@gmail.com'}
- {icon: 'rss-square', link: 'rss-feed.xml'}
