title:  Калина Алексей
tagline:  блог программиста

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/AlexeyKalina'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/dondigidon96'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:alexey.kalina96@gmail.com'}
- {icon: 'rss-square', link: 'https://www.github.com/AlexeyKalina/feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
